CREATE TABLE `client_intake_records` (
	`id` int AUTO_INCREMENT NOT NULL,
	`orderId` int,
	`paypalTransactionId` varchar(255),
	`purchasedService` varchar(255),
	`firstName` varchar(100) NOT NULL,
	`lastName` varchar(100) NOT NULL,
	`email` varchar(320) NOT NULL,
	`phone` varchar(50) NOT NULL,
	`cityState` varchar(255) NOT NULL,
	`bestContactTime` text,
	`employmentStatus` enum('employed_full_time','employed_part_time','casual','contractor','unemployed','student','other') NOT NULL,
	`currentJobTitle` varchar(255),
	`currentEmployer` varchar(255),
	`currentRoleOverview` text,
	`targetRoles` text NOT NULL,
	`preferredIndustries` text,
	`locationPreferences` text,
	`workArrangements` text,
	`jobAdLink1` varchar(500),
	`jobAdLink2` varchar(500),
	`jobAdLink3` varchar(500),
	`highestQualification` varchar(255),
	`institution` varchar(255),
	`yearCompleted` varchar(10),
	`additionalQualifications` text,
	`driversLicence` varchar(100),
	`highRiskLicences` text,
	`siteInductions` text,
	`securityClearances` text,
	`technicalSkills` text,
	`interpersonalStrengths` text,
	`employmentGaps` text,
	`keyAchievements` text,
	`preferredStyle` text,
	`hearAboutUs` varchar(255),
	`resumeFileUrl` text,
	`supportingDocsUrls` text,
	`status` enum('pending','in_progress','completed') NOT NULL DEFAULT 'pending',
	`adminNotes` text,
	`submittedAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `client_intake_records_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `employment_history` (
	`id` int AUTO_INCREMENT NOT NULL,
	`intakeRecordId` int NOT NULL,
	`jobTitle` varchar(255) NOT NULL,
	`employer` varchar(255) NOT NULL,
	`location` varchar(255),
	`startDate` varchar(20) NOT NULL,
	`endDate` varchar(20) NOT NULL,
	`employmentType` enum('full_time','part_time','casual','contract') NOT NULL,
	`keyResponsibilities` text,
	`keyAchievements` text,
	`sortOrder` int DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `employment_history_id` PRIMARY KEY(`id`)
);
